"""empty message

Revision ID: 5c672c831542
Revises: 
Create Date: 2022-07-29 14:53:39.787074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c672c831542'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post_File',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('if_pub', sa.Boolean(), nullable=True),
    sa.Column('if_share', sa.Boolean(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('iv', sa.String(), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('hmac_text', sa.String(), nullable=False),
    sa.Column('hashtext', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('file_id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('share_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('S_file_name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share__file',
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('share_code', sa.String(), nullable=False),
    sa.Column('TTL', sa.Integer(), nullable=True),
    sa.Column('DDL', sa.Integer(), nullable=True),
    sa.Column('share_time', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('iv', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('hmac', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('share_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USERS', name='userrole'), nullable=True),
    sa.Column('_password', sa.String(length=128), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('pub_key', sa.String(), nullable=False),
    sa.Column('sec_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    mysql_collate='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('share__file')
    op.drop_table('client')
    op.drop_table('Post_File')
    # ### end Alembic commands ###
